# Auto-generated by edagent-vivado
puts "INFO: Starting synthesis for uart_echo"

read_verilog {src/uart_rx.v}
read_verilog {src/uart_tx.v}
read_verilog {src/uart_top.v}
read_xdc {src/arty.xdc}

synth_design -top uart_top -part xc7a35ticsg324-1L

write_checkpoint -force {./checkpoints/post_synth.dcp}

report_timing_summary -file {./reports/post_synth_timing_summary.rpt}
report_utilization -file {./reports/post_synth_utilization.rpt}
report_drc -file {./reports/post_synth_drc.rpt}
exit
