# Auto-generated by edagent-vivado
puts "INFO: Starting synthesis for uart_demo"

read_verilog {E:/dev/edagent-vivado/examples/uart_demo/rtl/uart_top.v}
read_xdc {E:/dev/edagent-vivado/examples/uart_demo/constrs/top.xdc}

synth_design -top uart_top -part xc7a50tfgg484-2

write_checkpoint -force {E:/dev/edagent-vivado/examples/uart_demo/20260521_235015_synth/checkpoints/post_synth.dcp}

report_timing_summary -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_235015_synth/reports/post_synth_timing_summary.rpt}
report_utilization -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_235015_synth/reports/post_synth_utilization.rpt}
report_drc -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_235015_synth/reports/post_synth_drc.rpt}

puts "INFO: post_synth completed successfully"
exit
