# Auto-generated by edagent-vivado (impl)
puts "INFO: Starting impl for uart_demo"

open_checkpoint {/workspace/examples/uart_demo/20260523_053701_test_mock/checkpoints/post_synth.dcp}

opt_design
place_design
write_checkpoint -force {/workspace/examples/uart_demo/20260523_053701_test_mock/checkpoints/post_place.dcp}
route_design
write_checkpoint -force {/workspace/examples/uart_demo/20260523_053701_test_mock/checkpoints/post_route.dcp}

write_checkpoint -force {/workspace/examples/uart_demo/20260523_053701_test_mock/checkpoints/post_impl.dcp}

report_timing_summary -file {/workspace/examples/uart_demo/20260523_053701_test_mock/reports/post_impl_timing_summary.rpt}
report_utilization -file {/workspace/examples/uart_demo/20260523_053701_test_mock/reports/post_impl_utilization.rpt}
report_drc -file {/workspace/examples/uart_demo/20260523_053701_test_mock/reports/post_impl_drc.rpt}
exit
