# Exploratory runs use the same complete VC709 facts; no DRC is downgraded.
set_property PACKAGE_PIN H19 [get_ports sysclk_p]
set_property PACKAGE_PIN G18 [get_ports sysclk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sysclk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sysclk_n]
create_clock -name sysclk_200 -period 5.000 [get_ports sysclk_p]
set_property PACKAGE_PIN AV40 [get_ports cpu_reset]
set_property IOSTANDARD LVCMOS18 [get_ports cpu_reset]
set_property PACKAGE_PIN AU36 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
set_property PACKAGE_PIN AU33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]
set_false_path -from [get_ports uart_rxd] -to [get_pins u_uart/u_uart_rx/rxd_meta_reg/D]
set_false_path -from [get_ports cpu_reset]
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
