# Auto-generated by edagent-vivado (impl)
puts "INFO: Starting impl for uart_echo"

open_checkpoint {./checkpoints/post_synth.dcp}

opt_design
place_design
write_checkpoint -force {./checkpoints/post_place.dcp}
route_design
write_checkpoint -force {./checkpoints/post_route.dcp}

write_checkpoint -force {./checkpoints/post_impl.dcp}

report_timing_summary -file {./reports/post_impl_timing_summary.rpt}
report_utilization -file {./reports/post_impl_utilization.rpt}
report_drc -file {./reports/post_impl_drc.rpt}
exit
