
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
$targetBase64 = "CltDbWRsZXRCaW5kaW5nKCldCnBhcmFtKCkKU2V0LVN0cmljdE1vZGUgLVZlcnNpb24gTGF0ZXN0CiRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAiU3RvcCIKJFByb2dyZXNzUHJlZmVyZW5jZSA9ICJTaWxlbnRseUNvbnRpbnVlIgokZXhwZWN0ZWRDb21wdXRlciA9ICJERVNLVE9QLUUzODBMUjciCiRleHBlY3RlZElkZW50aXR5TmFtZSA9ICJkZXNrdG9wLWUzODBscjdcYWRtaW5pc3RyYXRvciIKJGV4cGVjdGVkSWRlbnRpdHlTaWQgPSAiUy0xLTUtMjEtMzQ0Mjg3MDcxMS0zMTkzODU1NjktMjI3NzgzMjk4Ny01MDAiCiRwb3dlcnNoZWxsUGF0aCA9ICJDOlxXaW5kb3dzXFN5c3RlbTMyXFdpbmRvd3NQb3dlclNoZWxsXHYxLjBccG93ZXJzaGVsbC5leGUiCiRleHBlY3RlZEVuY29kZWRMZW5ndGggPSAzMjU2CiRleHBlY3RlZEVuY29kZWRTaGEyNTYgPSAiZWM0YmI0NzdlOGU3YmQwYzA4NTUxODM3YjIxYWQ5MGUwNmFhYTNiYWIxMWU5NWI0NGNlZjVkZWUwYjZhMjJiYiIKJG1heGltdW1Db21tYW5kQnl0ZXMgPSA4MTkyCiRzdHJpY3RVdGY4ID0gW1RleHQuVVRGOEVuY29kaW5nXTo6bmV3KCRmYWxzZSwgJHRydWUpCiRzdHJpY3RVbmljb2RlID0gW1RleHQuVW5pY29kZUVuY29kaW5nXTo6bmV3KCRmYWxzZSwgJGZhbHNlLCAkdHJ1ZSkKCmZ1bmN0aW9uIEdldC1TaGEoW2J5dGVbXV0kQnl0ZXMpIHsKICAkc2hhID0gW1NlY3VyaXR5LkNyeXB0b2dyYXBoeS5TSEEyNTZdOjpDcmVhdGUoKQogIHRyeSB7IHJldHVybiBbQml0Q29udmVydGVyXTo6VG9TdHJpbmcoJHNoYS5Db21wdXRlSGFzaCgkQnl0ZXMpKS5SZXBsYWNlKCItIiwgIiIpLlRvTG93ZXJJbnZhcmlhbnQoKSB9CiAgZmluYWxseSB7ICRzaGEuRGlzcG9zZSgpIH0KfQoKZnVuY3Rpb24gR2V0LUNvdW50KFtzdHJpbmddJFZhbHVlLCBbc3RyaW5nXSRNYXJrZXIsIFtTdHJpbmdDb21wYXJpc29uXSRDb21wYXJpc29uKSB7CiAgJGNvdW50ID0gMAogICRvZmZzZXQgPSAwCiAgd2hpbGUgKCRvZmZzZXQgLWxlICRWYWx1ZS5MZW5ndGgpIHsKICAgICRmb3VuZCA9ICRWYWx1ZS5JbmRleE9mKCRNYXJrZXIsICRvZmZzZXQsICRDb21wYXJpc29uKQogICAgaWYgKCRmb3VuZCAtbHQgMCkgeyBicmVhayB9CiAgICAkY291bnQgKz0gMQogICAgJG9mZnNldCA9ICRmb3VuZCArICRNYXJrZXIuTGVuZ3RoCiAgfQogIHJldHVybiBbaW50XSRjb3VudAp9CgpmdW5jdGlvbiBDbGFzc2lmeShbc3RyaW5nXSRFeGVjdXRhYmxlLCBbc3RyaW5nXSRDb21tYW5kKSB7CiAgJGV4ZWN1dGFibGVDbGFzcyA9IGlmICgkRXhlY3V0YWJsZS5FcXVhbHMoJHBvd2Vyc2hlbGxQYXRoLCBbU3RyaW5nQ29tcGFyaXNvbl06Ok9yZGluYWwpKSB7ICJvcmRpbmFsX2V4YWN0IiB9CiAgICBlbHNlaWYgKCRFeGVjdXRhYmxlLkVxdWFscygkcG93ZXJzaGVsbFBhdGgsIFtTdHJpbmdDb21wYXJpc29uXTo6T3JkaW5hbElnbm9yZUNhc2UpKSB7ICJjYXNlX29ubHkiIH0KICAgIGVsc2UgeyAiZGlmZmVyZW50IiB9CiAgJGNvbW1hbmRCeXRlcyA9ICRzdHJpY3RVdGY4LkdldEJ5dGVzKCRDb21tYW5kKQogICRjb21tYW5kU2hhID0gR2V0LVNoYSAkY29tbWFuZEJ5dGVzCiAgJGNhbmRpZGF0ZSA9IGlmICgkY29tbWFuZEJ5dGVzLkxlbmd0aCAtZXEgMzM0NiAtYW5kICRjb21tYW5kU2hhIC1jZXEgImZhY2VmYzlmYTA1YTg3ODA0NDEyYmQ4YWI2Y2ZmNTM2NGEzNWM4NGYxMDQxMzQ1NGQzMDhjMTZmNDJmYzlkYzIiKSB7ICJiYXNlbmFtZV9leGFjdCIgfQogICAgZWxzZWlmICgkY29tbWFuZEJ5dGVzLkxlbmd0aCAtZXEgMzM4OSAtYW5kICRjb21tYW5kU2hhIC1jZXEgImEwZDc5ZDg5OTJlODgxZDExNGNkNGY3MGU2YjkxNjk3OGUzNzIxNjBmYjA2ZTNhMmJkNzgxYmRlYjIwZDA3NGYiKSB7ICJmaXhlZF9leGFjdCIgfQogICAgZWxzZWlmICgkY29tbWFuZEJ5dGVzLkxlbmd0aCAtZXEgMzM5MSAtYW5kICRjb21tYW5kU2hhIC1jZXEgIjIxNTIxMjAyZDhiNDUwODRkNzVlYzJkNzk3YjEyMTRlNDFkYTc2MGVmY2JlOTNlMzQwYjY4Y2EyZmIzZmQyNTEiKSB7ICJxdW90ZWRfZXhhY3QiIH0KICAgIGVsc2UgeyAibm9uZSIgfQogICRtYXJrZXIgPSAiIC1FbmNvZGVkQ29tbWFuZCAiCiAgJGV4YWN0TWFya2VycyA9IEdldC1Db3VudCAkQ29tbWFuZCAkbWFya2VyIChbU3RyaW5nQ29tcGFyaXNvbl06Ok9yZGluYWwpCiAgJGlnbm9yZUNhc2VNYXJrZXJzID0gR2V0LUNvdW50ICRDb21tYW5kICRtYXJrZXIgKFtTdHJpbmdDb21wYXJpc29uXTo6T3JkaW5hbElnbm9yZUNhc2UpCiAgJG1hcmtlckNsYXNzID0gaWYgKCRleGFjdE1hcmtlcnMgLWVxIDEgLWFuZCAkaWdub3JlQ2FzZU1hcmtlcnMgLWVxIDEpIHsgImV4YWN0IiB9CiAgICBlbHNlaWYgKCRleGFjdE1hcmtlcnMgLWVxIDAgLWFuZCAkaWdub3JlQ2FzZU1hcmtlcnMgLWVxIDEpIHsgImNhc2Vfb25seSIgfQogICAgZWxzZWlmICgkaWdub3JlQ2FzZU1hcmtlcnMgLWVxIDApIHsgIm1pc3NpbmciIH0KICAgIGVsc2UgeyAibXVsdGlwbGUiIH0KICAkcHJlZml4Q2xhc3MgPSAib3RoZXIiCiAgJHRva2VuID0gJG51bGwKICBpZiAoJGlnbm9yZUNhc2VNYXJrZXJzIC1lcSAxKSB7CiAgICAkbWFya2VyT2Zmc2V0ID0gJENvbW1hbmQuSW5kZXhPZigkbWFya2VyLCBbU3RyaW5nQ29tcGFyaXNvbl06Ok9yZGluYWxJZ25vcmVDYXNlKQogICAgJHByZWZpeCA9ICRDb21tYW5kLlN1YnN0cmluZygwLCAkbWFya2VyT2Zmc2V0KQogICAgJHRva2VuID0gJENvbW1hbmQuU3Vic3RyaW5nKCRtYXJrZXJPZmZzZXQgKyAkbWFya2VyLkxlbmd0aCkKICAgICR0YWlsID0gIiAtTm9Mb2dvIC1Ob1Byb2ZpbGUgLU5vbkludGVyYWN0aXZlIC1FeGVjdXRpb25Qb2xpY3kgQnlwYXNzIgogICAgJHByZWZpeGVzID0gQCgKICAgICAgW29yZGVyZWRdQHsgbmFtZSA9ICJiYXNlbmFtZSI7IHZhbHVlID0gInBvd2Vyc2hlbGwuZXhlIiArICR0YWlsIH0sCiAgICAgIFtvcmRlcmVkXUB7IG5hbWUgPSAiZml4ZWQiOyB2YWx1ZSA9ICRwb3dlcnNoZWxsUGF0aCArICR0YWlsIH0sCiAgICAgIFtvcmRlcmVkXUB7IG5hbWUgPSAicXVvdGVkIjsgdmFsdWUgPSAnIicgKyAkcG93ZXJzaGVsbFBhdGggKyAnIicgKyAkdGFpbCB9CiAgICApCiAgICBmb3JlYWNoICgkaXRlbSBpbiAkcHJlZml4ZXMpIHsKICAgICAgaWYgKCRwcmVmaXguRXF1YWxzKFtzdHJpbmddJGl0ZW0udmFsdWUsIFtTdHJpbmdDb21wYXJpc29uXTo6T3JkaW5hbCkpIHsgJHByZWZpeENsYXNzID0gW3N0cmluZ10kaXRlbS5uYW1lICsgIl9leGFjdCI7IGJyZWFrIH0KICAgICAgaWYgKCRwcmVmaXguRXF1YWxzKFtzdHJpbmddJGl0ZW0udmFsdWUsIFtTdHJpbmdDb21wYXJpc29uXTo6T3JkaW5hbElnbm9yZUNhc2UpKSB7ICRwcmVmaXhDbGFzcyA9IFtzdHJpbmddJGl0ZW0ubmFtZSArICJfY2FzZV9vbmx5IjsgYnJlYWsgfQogICAgfQogICAgaWYgKCRwcmVmaXhDbGFzcyAtY2VxICJvdGhlciIgLWFuZCAoJHByZWZpeC5TdGFydHNXaXRoKCJwb3dlcnNoZWxsLmV4ZSIsIFtTdHJpbmdDb21wYXJpc29uXTo6T3JkaW5hbElnbm9yZUNhc2UpIC1vcgogICAgICAkcHJlZml4LlN0YXJ0c1dpdGgoJHBvd2Vyc2hlbGxQYXRoLCBbU3RyaW5nQ29tcGFyaXNvbl06Ok9yZGluYWxJZ25vcmVDYXNlKSAtb3IKICAgICAgJHByZWZpeC5TdGFydHNXaXRoKCciJyArICRwb3dlcnNoZWxsUGF0aCArICciJywgW1N0cmluZ0NvbXBhcmlzb25dOjpPcmRpbmFsSWdub3JlQ2FzZSkpKSB7ICRwcmVmaXhDbGFzcyA9ICJzZXBhcmF0b3JfZHJpZnQiIH0KICB9CiAgJHRva2VuU2hhcGUgPSAibWlzc2luZyIKICAkbGVuZ3RoTWF0Y2hlcyA9ICRmYWxzZQogICRzaGFNYXRjaGVzID0gJGZhbHNlCiAgJGNhbm9uaWNhbCA9ICRmYWxzZQogICRyb3VuZHRyaXAgPSAkZmFsc2UKICBpZiAoJG51bGwgLW5lICR0b2tlbiAtYW5kICR0b2tlbi5MZW5ndGggLWd0IDApIHsKICAgICRhc2NpaSA9ICR0cnVlCiAgICAkd2hpdGVzcGFjZSA9ICRmYWxzZQogICAgZm9yZWFjaCAoJGNoYXJhY3RlciBpbiAkdG9rZW4uVG9DaGFyQXJyYXkoKSkgewogICAgICBpZiAoW2ludF1bY2hhcl0kY2hhcmFjdGVyIC1ndCAxMjcpIHsgJGFzY2lpID0gJGZhbHNlIH0KICAgICAgaWYgKFtjaGFyXTo6SXNXaGl0ZVNwYWNlKCRjaGFyYWN0ZXIpKSB7ICR3aGl0ZXNwYWNlID0gJHRydWUgfQogICAgfQogICAgaWYgKC1ub3QgJGFzY2lpKSB7ICR0b2tlblNoYXBlID0gIm5vbl9hc2NpaSIgfQogICAgZWxzZWlmICgkd2hpdGVzcGFjZSkgeyAkdG9rZW5TaGFwZSA9ICJ3aGl0ZXNwYWNlIiB9CiAgICBlbHNlaWYgKC1ub3QgW1RleHQuUmVndWxhckV4cHJlc3Npb25zLlJlZ2V4XTo6SXNNYXRjaCgkdG9rZW4sICdcQSg/OltBLVphLXowLTkrL117NH0pKig/OltBLVphLXowLTkrL117Mn09PXxbQS1aYS16MC05Ky9dezN9PSk/XHonLCBbVGV4dC5SZWd1bGFyRXhwcmVzc2lvbnMuUmVnZXhPcHRpb25zXTo6Q3VsdHVyZUludmFyaWFudCkpIHsgJHRva2VuU2hhcGUgPSAiaW52YWxpZF9iYXNlNjQiIH0KICAgIGVsc2UgewogICAgICAkdG9rZW5TaGFwZSA9ICJiYXNlNjRfc2hhcGUiCiAgICAgICR0b2tlbkJ5dGVzID0gW1RleHQuRW5jb2RpbmddOjpBU0NJSS5HZXRCeXRlcygkdG9rZW4pCiAgICAgICRsZW5ndGhNYXRjaGVzID0gJHRva2VuQnl0ZXMuTGVuZ3RoIC1lcSAkZXhwZWN0ZWRFbmNvZGVkTGVuZ3RoCiAgICAgICRzaGFNYXRjaGVzID0gKEdldC1TaGEgJHRva2VuQnl0ZXMpIC1jZXEgJGV4cGVjdGVkRW5jb2RlZFNoYTI1NgogICAgICB0cnkgewogICAgICAgICRkZWNvZGVkID0gW0NvbnZlcnRdOjpGcm9tQmFzZTY0U3RyaW5nKCR0b2tlbikKICAgICAgICAkY2Fub25pY2FsID0gW0NvbnZlcnRdOjpUb0Jhc2U2NFN0cmluZygkZGVjb2RlZCkgLWNlcSAkdG9rZW4KICAgICAgICBpZiAoJGNhbm9uaWNhbCkgeyAkc291cmNlID0gJHN0cmljdFVuaWNvZGUuR2V0U3RyaW5nKCRkZWNvZGVkKTsgJHJvdW5kdHJpcCA9ICRzdHJpY3RVbmljb2RlLkdldEJ5dGVzKCRzb3VyY2UpLkxlbmd0aCAtZXEgJGRlY29kZWQuTGVuZ3RoIH0KICAgICAgfSBjYXRjaCB7ICRjYW5vbmljYWwgPSAkZmFsc2U7ICRyb3VuZHRyaXAgPSAkZmFsc2UgfQogICAgfQogIH0KICAkc3RhZ2UgPSBpZiAoJGV4ZWN1dGFibGVDbGFzcyAtY25lICJvcmRpbmFsX2V4YWN0IikgeyAiZXhlY3V0YWJsZSIgfQogICAgZWxzZWlmICgkbWFya2VyQ2xhc3MgLWNuZSAiZXhhY3QiKSB7ICJtYXJrZXIiIH0KICAgIGVsc2VpZiAoJHByZWZpeENsYXNzIC1ub3RpbiBAKCJiYXNlbmFtZV9leGFjdCIsICJmaXhlZF9leGFjdCIsICJxdW90ZWRfZXhhY3QiKSkgeyAicHJlZml4IiB9CiAgICBlbHNlaWYgKCR0b2tlblNoYXBlIC1jbmUgImJhc2U2NF9zaGFwZSIpIHsgInRva2VuX3NoYXBlIiB9CiAgICBlbHNlaWYgKC1ub3QgJGxlbmd0aE1hdGNoZXMpIHsgImVuY29kZWRfbGVuZ3RoIiB9CiAgICBlbHNlaWYgKC1ub3QgJHNoYU1hdGNoZXMpIHsgImVuY29kZWRfaGFzaCIgfQogICAgZWxzZWlmICgtbm90ICRjYW5vbmljYWwpIHsgImNhbm9uaWNhbF9iYXNlNjQiIH0KICAgIGVsc2VpZiAoLW5vdCAkcm91bmR0cmlwKSB7ICJ1dGYxNmxlX3JvdW5kdHJpcCIgfQogICAgZWxzZSB7ICJub25lIiB9CiAgcmV0dXJuIFtvcmRlcmVkXUB7CiAgICBzY2hlbWEgPSAic3ludGhpYS1tNGYtcmVjZWl2ZXItcmVwcmVzZW50YXRpb24tY2xhc3NpZmljYXRpb24udjEiCiAgICBleGVjdXRhYmxlID0gJGV4ZWN1dGFibGVDbGFzcwogICAgY29tbWFuZF9jYW5kaWRhdGUgPSAkY2FuZGlkYXRlCiAgICBtYXJrZXIgPSAkbWFya2VyQ2xhc3MKICAgIHByZWZpeCA9ICRwcmVmaXhDbGFzcwogICAgdG9rZW5fc2hhcGUgPSAkdG9rZW5TaGFwZQogICAgZW5jb2RlZF9sZW5ndGhfbWF0Y2hlcyA9IFtib29sXSRsZW5ndGhNYXRjaGVzCiAgICBlbmNvZGVkX3NoYTI1Nl9tYXRjaGVzID0gW2Jvb2xdJHNoYU1hdGNoZXMKICAgIGNhbm9uaWNhbF9iYXNlNjQgPSBbYm9vbF0kY2Fub25pY2FsCiAgICB1dGYxNmxlX3JvdW5kdHJpcCA9IFtib29sXSRyb3VuZHRyaXAKICAgIGVhcmxpZXN0X21pc21hdGNoX3N0YWdlID0gJHN0YWdlCiAgfQp9CgokaWRlbnRpdHkgPSBbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NJZGVudGl0eV06OkdldEN1cnJlbnQoKQokcHJpbmNpcGFsID0gW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsXTo6bmV3KCRpZGVudGl0eSkKaWYgKFtFbnZpcm9ubWVudF06Ok1hY2hpbmVOYW1lIC1jbmUgJGV4cGVjdGVkQ29tcHV0ZXIgLW9yICRpZGVudGl0eS5OYW1lLlRvTG93ZXJJbnZhcmlhbnQoKSAtY25lICRleHBlY3RlZElkZW50aXR5TmFtZSAtb3IKICAkaWRlbnRpdHkuVXNlci5WYWx1ZSAtY25lICRleHBlY3RlZElkZW50aXR5U2lkIC1vciAtbm90ICRwcmluY2lwYWwuSXNJblJvbGUoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzQnVpbHRJblJvbGVdOjpBZG1pbmlzdHJhdG9yKSkgewogIHRocm93ICJNNEZfUkVDRUlWRVJfUkVQUkVTRU5UQVRJT05fSURFTlRJVFlfSU5WQUxJRCIKfQokc2VsZlBpZCA9IFt1aW50MzJdJFBJRAppZiAoJHNlbGZQaWQgLWx0IDEpIHsgdGhyb3cgIk00Rl9SRUNFSVZFUl9SRVBSRVNFTlRBVElPTl9QSURfSU5WQUxJRCIgfQokcXVlcnlUZXh0ID0gIlNFTEVDVCBQcm9jZXNzSWQsRXhlY3V0YWJsZVBhdGgsQ29tbWFuZExpbmUgRlJPTSBXaW4zMl9Qcm9jZXNzIFdIRVJFIFByb2Nlc3NJZD0iICsgJHNlbGZQaWQuVG9TdHJpbmcoW0dsb2JhbGl6YXRpb24uQ3VsdHVyZUluZm9dOjpJbnZhcmlhbnRDdWx0dXJlKQokY2xvY2sgPSBbRGlhZ25vc3RpY3MuU3RvcHdhdGNoXTo6U3RhcnROZXcoKQokZmFpbHVyZUNvZGUgPSAkbnVsbAokcm93cyA9IEAoKQp0cnkgeyAkcm93cyA9IEAoR2V0LUNpbUluc3RhbmNlIC1RdWVyeSAkcXVlcnlUZXh0IC1PcGVyYXRpb25UaW1lb3V0U2VjIDEwIC1FcnJvckFjdGlvbiBTdG9wKSB9CmNhdGNoIHsgJGZhaWx1cmVDb2RlID0gInF1ZXJ5X2ZhaWxlZCIgfQokY2xvY2suU3RvcCgpCmlmICgkcm93cy5Db3VudCAtZ3QgMikgeyB0aHJvdyAiTTRGX1JFQ0VJVkVSX1JFUFJFU0VOVEFUSU9OX0NBUkRJTkFMSVRZX0JPVU5EIiB9CmlmICgkbnVsbCAtZXEgJGZhaWx1cmVDb2RlIC1hbmQgJHJvd3MuQ291bnQgLW5lIDEpIHsgJGZhaWx1cmVDb2RlID0gImNhcmRpbmFsaXR5IiB9CiRhY3R1YWwgPSBbb3JkZXJlZF1AeyBzY2hlbWEgPSAic3ludGhpYS1tNGYtcmVjZWl2ZXItcmVwcmVzZW50YXRpb24tYWN0dWFsLnYxIjsgcmV0dXJuZWRfY291bnQgPSBbaW50XSRyb3dzLkNvdW50OyBleGVjdXRhYmxlX3BhdGggPSAkbnVsbDsgY29tbWFuZF9wcmVzZW50ID0gJGZhbHNlOyBjb21tYW5kX3V0ZjhfbGVuZ3RoID0gJG51bGw7IGNvbW1hbmRfc2hhMjU2ID0gJG51bGwgfQokY2xhc3NpZmljYXRpb24gPSAkbnVsbAppZiAoJHJvd3MuQ291bnQgLWVxIDEpIHsKICAkcm93ID0gJHJvd3NbMF0KICBpZiAoJHJvdy5Qcm9jZXNzSWQgLWlzbm90IFt1aW50MzJdIC1vciBbdWludDMyXSRyb3cuUHJvY2Vzc0lkIC1uZSAkc2VsZlBpZCkgeyAkZmFpbHVyZUNvZGUgPSAicGlkX2JpbmRpbmciIH0KICBlbHNlaWYgKCRudWxsIC1lcSAkcm93LkV4ZWN1dGFibGVQYXRoIC1vciAkbnVsbCAtZXEgJHJvdy5Db21tYW5kTGluZSkgeyAkZmFpbHVyZUNvZGUgPSAibWlzc2luZ19wcm9wZXJ0eSIgfQogIGVsc2UgewogICAgJGV4ZWN1dGFibGUgPSBbc3RyaW5nXSRyb3cuRXhlY3V0YWJsZVBhdGgKICAgICRleGVjdXRhYmxlQnl0ZXMgPSAkc3RyaWN0VXRmOC5HZXRCeXRlcygkZXhlY3V0YWJsZSkKICAgIGlmICgkZXhlY3V0YWJsZUJ5dGVzLkxlbmd0aCAtbHQgMSAtb3IgJGV4ZWN1dGFibGVCeXRlcy5MZW5ndGggLWd0IDEwMjQgLW9yICRleGVjdXRhYmxlIC1ub3RtYXRjaCAnXEFbQS1aYS16XTpcXFteXHgwMC1ceDFmXHg3Zl0rXC5leGVceicpIHsgJGZhaWx1cmVDb2RlID0gInVuc2FmZV9leGVjdXRhYmxlIiB9CiAgICBlbHNlIHsKICAgICAgJGFjdHVhbC5leGVjdXRhYmxlX3BhdGggPSAkZXhlY3V0YWJsZQogICAgICAkY29tbWFuZCA9IFtzdHJpbmddJHJvdy5Db21tYW5kTGluZQogICAgICAkY29tbWFuZEJ5dGVzID0gJHN0cmljdFV0ZjguR2V0Qnl0ZXMoJGNvbW1hbmQpCiAgICAgIGlmICgkY29tbWFuZEJ5dGVzLkxlbmd0aCAtbHQgMSkgeyAkZmFpbHVyZUNvZGUgPSAibWlzc2luZ19jb21tYW5kIiB9CiAgICAgIGVsc2VpZiAoJGNvbW1hbmRCeXRlcy5MZW5ndGggLWd0ICRtYXhpbXVtQ29tbWFuZEJ5dGVzKSB7ICRmYWlsdXJlQ29kZSA9ICJjb21tYW5kX2JvdW5kIiB9CiAgICAgIGVsc2UgewogICAgICAgICRhY3R1YWwuY29tbWFuZF9wcmVzZW50ID0gJHRydWUKICAgICAgICAkYWN0dWFsLmNvbW1hbmRfdXRmOF9sZW5ndGggPSBbaW50XSRjb21tYW5kQnl0ZXMuTGVuZ3RoCiAgICAgICAgJGFjdHVhbC5jb21tYW5kX3NoYTI1NiA9IEdldC1TaGEgJGNvbW1hbmRCeXRlcwogICAgICAgICRjbGFzc2lmaWNhdGlvbiA9IENsYXNzaWZ5ICRleGVjdXRhYmxlICRjb21tYW5kCiAgICAgIH0KICAgIH0KICB9Cn0KJHN0YXR1cyA9IGlmICgkbnVsbCAtbmUgJGZhaWx1cmVDb2RlKSB7ICJpbmRldGVybWluYXRlIiB9IGVsc2VpZiAoJGNsYXNzaWZpY2F0aW9uLmVhcmxpZXN0X21pc21hdGNoX3N0YWdlIC1jZXEgIm5vbmUiKSB7ICJyZXByZXNlbnRhdGlvbl9tYXRjaCIgfSBlbHNlIHsgInJlcHJlc2VudGF0aW9uX21pc21hdGNoIiB9CiRvdXRwdXQgPSBbb3JkZXJlZF1AewogIHNjaGVtYSA9ICJzeW50aGlhLW00Zi1jdXJyZW50LXJlY2VpdmVyLXJlcHJlc2VudGF0aW9uLWRpYWdub3N0aWMtMDkudjEiCiAgcHJlZGVjZXNzb3JfYXR0ZW1wdCA9IFtvcmRlcmVkXUB7IHNjaGVtYSA9ICJzeW50aGlhLW00Zi1wcmVkZWNlc3Nvci1lZmZlY3QtMDkudjEiOyBhdHRlbXB0ID0gIl8wOCI7IGVmZmVjdF9zdGF0ZSA9ICJ1bmtub3duIjsgcXVlcmllZCA9ICRmYWxzZTsgY2xlYW51cF9hdHRlbXB0ZWQgPSAkZmFsc2UgfQogIHN0YXR1cyA9ICRzdGF0dXMKICBzY29wZSA9ICJjdXJyZW50X3BpZF9leGFjdF9jaW1fb25seSIKICByZXNpZHVlX3N0YXRlX2V2YWx1YXRlZCA9ICRmYWxzZQogIHByb3ZpZGVyX2FjdGl2YXRpb25fbWF5X2NyZWF0ZV9wcm9jZXNzZXMgPSAkdHJ1ZQogIGZhaWx1cmVfY29kZSA9ICRmYWlsdXJlQ29kZQogIHF1ZXJ5ID0gW29yZGVyZWRdQHsgc2NoZW1hID0gInN5bnRoaWEtbTRmLXJlY2VpdmVyLXJlcHJlc2VudGF0aW9uLXF1ZXJ5LnYxIjsgcmV0dXJuZWRfY291bnQgPSBbaW50XSRyb3dzLkNvdW50OyBlbGFwc2VkX3RpY2tzID0gW2ludDY0XSRjbG9jay5FbGFwc2VkVGlja3M7IHN0b3B3YXRjaF9mcmVxdWVuY3kgPSBbaW50NjRdW0RpYWdub3N0aWNzLlN0b3B3YXRjaF06OkZyZXF1ZW5jeSB9CiAgZXhwZWN0ZWQgPSBbb3JkZXJlZF1AewogICAgc2NoZW1hID0gInN5bnRoaWEtbTRmLXJlY2VpdmVyLXJlcHJlc2VudGF0aW9uLWV4cGVjdGVkLnYxIgogICAgZXhlY3V0YWJsZV9wYXRoID0gJHBvd2Vyc2hlbGxQYXRoCiAgICBlbmNvZGVkX2xlbmd0aCA9ICRleHBlY3RlZEVuY29kZWRMZW5ndGgKICAgIGVuY29kZWRfc2hhMjU2ID0gJGV4cGVjdGVkRW5jb2RlZFNoYTI1NgogICAgYmFzZW5hbWVfY29tbWFuZF9sZW5ndGggPSAzMzQ2CiAgICBiYXNlbmFtZV9jb21tYW5kX3NoYTI1NiA9ICJmYWNlZmM5ZmEwNWE4NzgwNDQxMmJkOGFiNmNmZjUzNjRhMzVjODRmMTA0MTM0NTRkMzA4YzE2ZjQyZmM5ZGMyIgogICAgZml4ZWRfY29tbWFuZF9sZW5ndGggPSAzMzg5CiAgICBmaXhlZF9jb21tYW5kX3NoYTI1NiA9ICJhMGQ3OWQ4OTkyZTg4MWQxMTRjZDRmNzBlNmI5MTY5NzhlMzcyMTYwZmIwNmUzYTJiZDc4MWJkZWIyMGQwNzRmIgogICAgcXVvdGVkX2NvbW1hbmRfbGVuZ3RoID0gMzM5MQogICAgcXVvdGVkX2NvbW1hbmRfc2hhMjU2ID0gIjIxNTIxMjAyZDhiNDUwODRkNzVlYzJkNzk3YjEyMTRlNDFkYTc2MGVmY2JlOTNlMzQwYjY4Y2EyZmIzZmQyNTEiCiAgfQogIGFjdHVhbCA9ICRhY3R1YWwKICBjbGFzc2lmaWNhdGlvbiA9ICRjbGFzc2lmaWNhdGlvbgp9CiRqc29uID0gJG91dHB1dCB8IENvbnZlcnRUby1Kc29uIC1EZXB0aCA1IC1Db21wcmVzcwppZiAoJHN0cmljdFV0ZjguR2V0Qnl0ZUNvdW50KCRqc29uKSAtZ3QgMTA0ODU3NikgeyB0aHJvdyAiTTRGX1JFQ0VJVkVSX1JFUFJFU0VOVEFUSU9OX09VVFBVVF9CT1VORCIgfQpbQ29uc29sZV06Ok91dC5Xcml0ZUxpbmUoJGpzb24pCg=="
$expectedTargetLength = 10222
$expectedTargetSha256 = "76633aaa8a00850501a92d92696b301bd6631d245777c58d943489dce4adfef9"
$maximumParseErrors = 32
$maximumParseErrorCount = 128
$maximumMessageBytes = 8192
$strictUtf8 = New-Object System.Text.UTF8Encoding($false, $true)

function Get-BytesSha256([byte[]]$Bytes) {
  $sha256 = [Security.Cryptography.SHA256]::Create()
  try {
    return [BitConverter]::ToString($sha256.ComputeHash($Bytes)).Replace("-", "").ToLowerInvariant()
  } finally {
    $sha256.Dispose()
  }
}

function Get-MessageFact([string]$Message) {
  $bytes = $strictUtf8.GetBytes($Message)
  if ($bytes.Length -gt $maximumMessageBytes) {
    throw "M4F_RECEIVER_REPRESENTATION_PARSE_09_MESSAGE_BOUND"
  }
  return [ordered]@{
    length = [int]$bytes.Length
    sha256 = Get-BytesSha256 $bytes
  }
}

function Get-ExceptionFact([Exception]$Exception) {
  $message = Get-MessageFact ([string]$Exception.Message)
  return [ordered]@{
    schema = "synthia-m4f-receiver-representation-parse-09-exception.v1"
    type = [string]$Exception.GetType().FullName
    hresult = [int]$Exception.HResult
    message_utf8_length = [int]$message.length
    message_utf8_sha256 = [string]$message.sha256
  }
}

$targetBytes = [Convert]::FromBase64String($targetBase64)
if ([Convert]::ToBase64String($targetBytes) -cne $targetBase64 -or
  $targetBytes.Length -ne $expectedTargetLength -or
  (Get-BytesSha256 $targetBytes) -cne $expectedTargetSha256) {
  throw "M4F_RECEIVER_REPRESENTATION_PARSE_09_TARGET_INVALID"
}
$targetSource = $strictUtf8.GetString($targetBytes)
if ($strictUtf8.GetBytes($targetSource).Length -ne $targetBytes.Length) {
  throw "M4F_RECEIVER_REPRESENTATION_PARSE_09_TARGET_UTF8_INVALID"
}

$tokens = $null
$parseErrors = $null
$parsedTarget = [System.Management.Automation.Language.Parser]::ParseInput($targetSource, [ref]$tokens, [ref]$parseErrors)
if ($parseErrors.Count -gt $maximumParseErrorCount) {
  throw "M4F_RECEIVER_REPRESENTATION_PARSE_09_ERROR_CARDINALITY"
}
$parsedExtentText = [string]$parsedTarget.Extent.Text
$parsedExtentBytes = $strictUtf8.GetBytes($parsedExtentText)
$parseErrorFacts = @()
foreach ($parseError in @($parseErrors | Select-Object -First $maximumParseErrors)) {
  $message = Get-MessageFact ([string]$parseError.Message)
  $parseErrorFacts += [ordered]@{
    schema = "synthia-m4f-receiver-representation-parse-09-error.v1"
    error_id = [string]$parseError.ErrorId
    message_utf8_length = [int]$message.length
    message_utf8_sha256 = [string]$message.sha256
    start_offset = [int]$parseError.Extent.StartOffset
    end_offset = [int]$parseError.Extent.EndOffset
  }
}

$constructedTarget = $null
$scriptBlockCreateException = $null
try {
  $constructedTarget = [ScriptBlock]::Create($targetSource)
} catch {
  $scriptBlockCreateException = Get-ExceptionFact $_.Exception
}
$targetScriptblockConstructed = $null -ne $constructedTarget
$constructedAstType = $null
$constructedExtentStartOffset = $null
$constructedExtentEndOffset = $null
$constructedExtentCharacterLength = $null
$constructedExtentUtf8Length = $null
$constructedExtentSha256 = $null
if ($targetScriptblockConstructed) {
  $constructedExtentText = [string]$constructedTarget.Ast.Extent.Text
  $constructedExtentBytes = $strictUtf8.GetBytes($constructedExtentText)
  $constructedAstType = [string]$constructedTarget.Ast.GetType().FullName
  $constructedExtentStartOffset = [int]$constructedTarget.Ast.Extent.StartOffset
  $constructedExtentEndOffset = [int]$constructedTarget.Ast.Extent.EndOffset
  $constructedExtentCharacterLength = [int]$constructedExtentText.Length
  $constructedExtentUtf8Length = [int]$constructedExtentBytes.Length
  $constructedExtentSha256 = Get-BytesSha256 $constructedExtentBytes
}
$status = if ($parseErrors.Count -eq 0 -and $targetScriptblockConstructed) {
  "parsed_not_invoked"
} else {
  "parse_rejected"
}
$output = [ordered]@{
  schema = "synthia-m4f-receiver-representation-parse-09-gate.v1"
  status = $status
  target_artifact_length = $expectedTargetLength
  target_artifact_sha256 = $expectedTargetSha256
  target_source_character_length = [int]$targetSource.Length
  target_source_utf8_length = [int]$targetBytes.Length
  target_source_sha256 = Get-BytesSha256 $targetBytes
  powershell_edition = [string]$PSVersionTable.PSEdition
  powershell_version = [string]$PSVersionTable.PSVersion.ToString()
  process_bitness = [int]([IntPtr]::Size * 8)
  language_mode = [string]$ExecutionContext.SessionState.LanguageMode
  parser_ast_type = [string]$parsedTarget.GetType().FullName
  parser_extent_start_offset = [int]$parsedTarget.Extent.StartOffset
  parser_extent_end_offset = [int]$parsedTarget.Extent.EndOffset
  parser_extent_character_length = [int]$parsedExtentText.Length
  parser_extent_utf8_length = [int]$parsedExtentBytes.Length
  parser_extent_sha256 = Get-BytesSha256 $parsedExtentBytes
  parse_error_count = [int]$parseErrors.Count
  parse_errors_truncated = [bool]($parseErrors.Count -gt $parseErrorFacts.Count)
  parse_errors = @($parseErrorFacts)
  target_scriptblock_constructed = [bool]$targetScriptblockConstructed
  constructed_ast_type = $constructedAstType
  constructed_extent_start_offset = $constructedExtentStartOffset
  constructed_extent_end_offset = $constructedExtentEndOffset
  constructed_extent_character_length = $constructedExtentCharacterLength
  constructed_extent_utf8_length = $constructedExtentUtf8Length
  constructed_extent_sha256 = $constructedExtentSha256
  scriptblock_create_exception = $scriptBlockCreateException
  target_body_not_invoked = $true
}
$json = $output | ConvertTo-Json -Depth 5 -Compress
if ($strictUtf8.GetByteCount($json) -gt 1048576) {
  throw "M4F_RECEIVER_REPRESENTATION_PARSE_09_OUTPUT_BOUND"
}
[Console]::Out.WriteLine($json)
