"""Tcl templates for Vivado synthesis/implementation."""
from __future__ import annotations
from pathlib import Path
from edagent_vivado.harness.manifest import Manifest

def _esc(p: Path) -> str: return str(p).replace("\\", "/").replace(" ", r"\ ")

def generate_synth_tcl(manifest: Manifest, workspace_root: Path, directive: str | None = None, retiming: bool = False) -> str:
    lines = ["# Auto-generated by edagent-vivado", f'puts "INFO: Starting synthesis for {manifest.name()}"', ""]
    for r in manifest.rtl_paths():
        if r.suffix == ".v": lines.append(f"read_verilog {{{_esc(r)}}}")
        elif r.suffix == ".sv": lines.append(f"read_verilog -sv {{{_esc(r)}}}")
        elif r.suffix in (".vhd", ".vhdl"): lines.append(f"read_vhdl {{{_esc(r)}}}")
    for x in manifest.xdc_paths(): lines.append(f"read_xdc {{{_esc(x)}}}")
    lines.append("")
    cmd = f"synth_design -top {manifest.top()} -part {manifest.part()}"
    if directive: cmd += f" -directive {directive}"
    if retiming: cmd += " -retiming"
    lines.append(cmd); lines.append("")
    _write_outputs(lines, workspace_root, "post_synth")
    lines.append("exit")
    return "\n".join(lines) + "\n"

def generate_impl_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (impl)", f'puts "INFO: Starting impl for {manifest.name()}"', ""]
    ckpt = _esc(workspace_root / "checkpoints" / "post_synth.dcp")
    lines.append(f"open_checkpoint {{{ckpt}}}"); lines.append("")
    lines.append("opt_design"); lines.append("place_design")
    lines.append(f"write_checkpoint -force {{{_esc(workspace_root / 'checkpoints' / 'post_place.dcp')}}}")
    lines.append("route_design")
    lines.append(f"write_checkpoint -force {{{_esc(workspace_root / 'checkpoints' / 'post_route.dcp')}}}")
    lines.append("")
    _write_outputs(lines, workspace_root, "post_impl")
    lines.append("exit")
    return "\n".join(lines) + "\n"

def generate_project_synth_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (project mode)"]
    pd = _esc(workspace_root / "vivado_project")
    lines.append(f"create_project {{{manifest.name()}}} {{{pd}}} -part {manifest.part()}")
    for r in manifest.rtl_paths():
        if r.suffix == ".v": lines.append(f"read_verilog {{{_esc(r)}}}")
        elif r.suffix == ".sv": lines.append(f"read_verilog -sv {{{_esc(r)}}}")
    for x in manifest.xdc_paths(): lines.append(f"read_xdc {{{_esc(x)}}}")
    lines.append(f"set_property top {manifest.top()} [current_fileset]")
    lines.append("launch_runs synth_1 -jobs 4"); lines.append("wait_on_run synth_1")
    lines.append("open_run synth_1")
    _write_outputs(lines, workspace_root, "post_synth")
    lines.append("exit")
    return "\n".join(lines) + "\n"

def generate_project_impl_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (project mode impl)"]
    lines.append(f"open_project {{{_esc(workspace_root / 'vivado_project')}}}")
    lines.append("launch_runs impl_1 -jobs 4"); lines.append("wait_on_run impl_1")
    lines.append("open_run impl_1")
    _write_outputs(lines, workspace_root, "post_impl")
    lines.append("exit")
    return "\n".join(lines) + "\n"

def _write_outputs(lines: list, workspace_root: Path, prefix: str) -> None:
    ckpt = _esc(workspace_root / "checkpoints" / f"{prefix}.dcp")
    lines.append(f"write_checkpoint -force {{{ckpt}}}"); lines.append("")
    rp = workspace_root / "reports"
    lines.append(f"report_timing_summary -file {{{_esc(rp / f'{prefix}_timing_summary.rpt')}}}")
    lines.append(f"report_utilization -file {{{_esc(rp / f'{prefix}_utilization.rpt')}}}")
    lines.append(f"report_drc -file {{{_esc(rp / f'{prefix}_drc.rpt')}}}")
