"""Tcl templates — generate Vivado Tcl scripts from manifest."""

from __future__ import annotations
from pathlib import Path
from edagent_vivado.harness.manifest import Manifest


def _esc(p: Path) -> str:
    return str(p).replace("\\", "/").replace(" ", r"\ ")


def generate_synth_tcl(manifest: Manifest, workspace_root: Path, directive: str | None = None, retiming: bool = False) -> str:
    lines = ["# Auto-generated by edagent-vivado", f'puts "INFO: Starting synthesis for {manifest.name()}"', ""]
    _read_sources(lines, manifest)
    lines.append("")
    cmd = f"synth_design -top {manifest.top()} -part {manifest.part()}"
    if directive: cmd += f" -directive {directive}"
    if retiming: cmd += " -retiming"
    lines.append(cmd)
    lines.append("")
    _write_outputs(lines, workspace_root, "post_synth")
    lines.append("exit")
    return "\n".join(lines) + "\n"


def generate_impl_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (implementation)", f'puts "INFO: Starting implementation for {manifest.name()}"', ""]
    ckpt = _esc(workspace_root / "checkpoints" / "post_synth.dcp")
    lines.append(f"open_checkpoint {{{ckpt}}}")
    lines.append("")
    lines.append("opt_design"); lines.append("place_design")
    lines.append(f"write_checkpoint -force {{{_esc(workspace_root / 'checkpoints' / 'post_place.dcp')}}}")
    lines.append("route_design")
    lines.append(f"write_checkpoint -force {{{_esc(workspace_root / 'checkpoints' / 'post_route.dcp')}}}")
    lines.append("")
    _write_outputs(lines, workspace_root, "post_impl")
    lines.append("exit")
    return "\n".join(lines) + "\n"


def generate_project_synth_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (project mode)", f'puts "INFO: Creating project {manifest.name()}"', ""]
    proj_dir = _esc(workspace_root / "vivado_project")
    lines.append(f"create_project {{{manifest.name()}}} {{{proj_dir}}} -part {manifest.part()}")
    lines.append("")
    _read_sources(lines, manifest)
    lines.append(f"set_property top {manifest.top()} [current_fileset]")
    lines.append("")
    lines.append("launch_runs synth_1 -jobs 4"); lines.append("wait_on_run synth_1")
    lines.append("")
    lines.append("open_run synth_1")
    _write_outputs(lines, workspace_root, "post_synth")
    lines.append("exit")
    return "\n".join(lines) + "\n"


def generate_project_impl_tcl(manifest: Manifest, workspace_root: Path) -> str:
    lines = ["# Auto-generated by edagent-vivado (project mode impl)"]
    lines.append(f"open_project {{{_esc(workspace_root / 'vivado_project')}}}")
    lines.append("")
    lines.append("launch_runs impl_1 -jobs 4"); lines.append("wait_on_run impl_1")
    lines.append("")
    lines.append("open_run impl_1")
    _write_outputs(lines, workspace_root, "post_impl")
    lines.append("exit")
    return "\n".join(lines) + "\n"


def _read_sources(lines: list, manifest: Manifest) -> None:
    for rtl in manifest.rtl_paths():
        if rtl.suffix == ".v": lines.append(f"read_verilog {{{_esc(rtl)}}}")
        elif rtl.suffix == ".sv": lines.append(f"read_verilog -sv {{{_esc(rtl)}}}")
        elif rtl.suffix in (".vhd", ".vhdl"): lines.append(f"read_vhdl {{{_esc(rtl)}}}")
    for xdc in manifest.xdc_paths():
        lines.append(f"read_xdc {{{_esc(xdc)}}}")


def _write_outputs(lines: list, workspace_root: Path, prefix: str) -> None:
    ckpt = _esc(workspace_root / "checkpoints" / f"{prefix}.dcp")
    lines.append(f"write_checkpoint -force {{{ckpt}}}")
    lines.append("")
    reports = workspace_root / "reports"
    lines.append(f"report_timing_summary -file {{{_esc(reports / f'{prefix}_timing_summary.rpt')}}}")
    lines.append(f"report_utilization -file {{{_esc(reports / f'{prefix}_utilization.rpt')}}}")
    lines.append(f"report_drc -file {{{_esc(reports / f'{prefix}_drc.rpt')}}}")
    lines.append("")
