FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1

WORKDIR /app
COPY pyproject.toml ./
COPY src ./src

RUN pip install -e ".[postgres,redis,worker]"

ENV SYNTHIA_WORKER_POOL=vivado

CMD ["synthia-worker", "--pool", "vivado"]
