# Auto-generated by edagent-vivado
puts "INFO: Starting synthesis for uart_demo"

read_verilog {/Users/wenzhuolin/dev/edagent/examples/uart_demo/rtl/uart_top.v}
read_xdc {/Users/wenzhuolin/dev/edagent/examples/uart_demo/constrs/top.xdc}

synth_design -top uart_top -part xc7a50tfgg484-2

write_checkpoint -force {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_160410_batch_synth/checkpoints/post_synth.dcp}

report_timing_summary -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_160410_batch_synth/reports/post_synth_timing_summary.rpt}
report_utilization -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_160410_batch_synth/reports/post_synth_utilization.rpt}
report_drc -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_160410_batch_synth/reports/post_synth_drc.rpt}
exit
