# Auto-generated by edagent-vivado
puts "INFO: Starting synthesis for unnamed"


synth_design -top top -part 

write_checkpoint -force {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_190417_batch_synth/checkpoints/post_synth.dcp}

report_timing_summary -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_190417_batch_synth/reports/post_synth_timing_summary.rpt}
report_utilization -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_190417_batch_synth/reports/post_synth_utilization.rpt}
report_drc -file {/Users/wenzhuolin/dev/edagent/examples/uart_demo/20260523_190417_batch_synth/reports/post_synth_drc.rpt}
exit
