"""Vivado connector capability matrix — SPEC §9B.6 (tier 1)."""

from __future__ import annotations

from edagent_vivado.connectors.base.types import ToolCapability

VIVADO_CAPABILITIES: list[ToolCapability] = [
    ToolCapability(
        connector_id="vivado",
        capability_id="detect_environment",
        display_name="Detect Vivado Environment",
        stage="validate",
        input_schema={},
        outputs=["environment"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="validate_project",
        display_name="Validate Project Manifest",
        stage="validate",
        input_schema={"manifest_path": "string"},
        outputs=["validation"],
        risk_level="low",
        requires_approval=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_synthesis",
        display_name="Vivado Synthesis",
        stage="synth",
        input_schema={"manifest_path": "string", "strategy": "string"},
        outputs=["vivado_log", "timing_summary", "utilization", "drc", "post_synth_dcp"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_implementation",
        display_name="Vivado Implementation",
        stage="impl",
        input_schema={"manifest_path": "string"},
        outputs=["vivado_log", "timing_summary", "utilization", "drc", "post_impl_dcp"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_simulation",
        display_name="Vivado Simulation",
        stage="sim",
        input_schema={"manifest_path": "string"},
        outputs=["sim_log"],
        risk_level="low",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_timing_summary",
        display_name="Report Timing Summary",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["timing_summary"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_utilization",
        display_name="Report Utilization",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["utilization"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_drc",
        display_name="Report DRC",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["drc"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_methodology",
        display_name="Report Methodology",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["methodology"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="parse_vivado_log",
        display_name="Parse Vivado Log",
        stage="report",
        input_schema={"log_path": "string"},
        outputs=["log_summary"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="classify_vivado_error",
        display_name="Classify Vivado Error",
        stage="diagnose",
        input_schema={"log_path": "string"},
        outputs=["error_summary"],
        risk_level="low",
        requires_approval=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="import_xpr",
        display_name="Import Vivado .xpr Project",
        stage="project",
        input_schema={"xpr_path": "string"},
        outputs=["project_summary", "internal_manifest"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="scan_project",
        display_name="Scan Directory for FPGA Sources",
        stage="project",
        input_schema={"root_path": "string"},
        outputs=["project_summary"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="create_vivado_project",
        display_name="Create Vivado .xpr from Manifest",
        stage="project",
        input_schema={"manifest_path": "string", "output_dir": "string"},
        outputs=["xpr_path"],
        risk_level="medium",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="sync_xpr_manifest",
        display_name="Sync xpr ↔ Manifest Fingerprint",
        stage="project",
        input_schema={"project_id": "string"},
        outputs=["sync_result"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="generate_bitstream",
        display_name="Generate Bitstream",
        stage="bitstream",
        input_schema={"manifest_path": "string", "from_dcp": "string"},
        outputs=["bitstream", "bitstream_log"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="collect_bitstream",
        display_name="Collect Generated Bitstream Artifacts",
        stage="bitstream",
        input_schema={"run_id": "string"},
        outputs=["bitstream", "bitstream_log"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_full_flow",
        display_name="Synthesis + Implementation + Bitstream",
        stage="flow",
        input_schema={"manifest_path": "string", "stages": "array"},
        outputs=["vivado_log", "timing_summary", "utilization", "drc", "bitstream"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="program_device",
        display_name="Program FPGA Device (.bit)",
        stage="hardware",
        input_schema={
            "hardware_session_id": "string",
            "bitstream_artifact_id": "string",
        },
        outputs=["job_id", "success"],
        risk_level="high",
        requires_approval=True,
        produces_reports=False,
    ),
]
