"""Vivado connector capability matrix — SPEC §9B.6 (tier 1)."""

from __future__ import annotations

from edagent_vivado.connectors.base.types import ToolCapability

VIVADO_CAPABILITIES: list[ToolCapability] = [
    ToolCapability(
        connector_id="vivado",
        capability_id="detect_environment",
        display_name="Detect Vivado Environment",
        stage="validate",
        input_schema={},
        outputs=["environment"],
        risk_level="low",
        requires_approval=False,
        produces_reports=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="validate_project",
        display_name="Validate Project Manifest",
        stage="validate",
        input_schema={"manifest_path": "string"},
        outputs=["validation"],
        risk_level="low",
        requires_approval=False,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_synthesis",
        display_name="Vivado Synthesis",
        stage="synth",
        input_schema={"manifest_path": "string", "strategy": "string"},
        outputs=["vivado_log", "timing_summary", "utilization", "drc", "post_synth_dcp"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_implementation",
        display_name="Vivado Implementation",
        stage="impl",
        input_schema={"manifest_path": "string"},
        outputs=["vivado_log", "timing_summary", "utilization", "drc", "post_impl_dcp"],
        risk_level="medium",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="run_simulation",
        display_name="Vivado Simulation",
        stage="sim",
        input_schema={"manifest_path": "string"},
        outputs=["sim_log"],
        risk_level="low",
        requires_approval=True,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_timing_summary",
        display_name="Report Timing Summary",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["timing_summary"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_utilization",
        display_name="Report Utilization",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["utilization"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_drc",
        display_name="Report DRC",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["drc"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="report_methodology",
        display_name="Report Methodology",
        stage="report",
        input_schema={"report_path": "string"},
        outputs=["methodology"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="parse_vivado_log",
        display_name="Parse Vivado Log",
        stage="report",
        input_schema={"log_path": "string"},
        outputs=["log_summary"],
        risk_level="low",
        requires_approval=False,
        produces_reports=True,
    ),
    ToolCapability(
        connector_id="vivado",
        capability_id="classify_vivado_error",
        display_name="Classify Vivado Error",
        stage="diagnose",
        input_schema={"log_path": "string"},
        outputs=["error_summary"],
        risk_level="low",
        requires_approval=False,
    ),
]
