# Auto-generated by edagent-vivado (implementation)
puts "INFO: Starting implementation for uart_demo"

open_checkpoint {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/checkpoints/post_synth.dcp}

opt_design
place_design
write_checkpoint -force {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/checkpoints/post_place.dcp}
route_design
write_checkpoint -force {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/checkpoints/post_route.dcp}

write_checkpoint -force {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/checkpoints/post_impl.dcp}

report_timing_summary -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/reports/post_impl_timing_summary.rpt}
report_utilization -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/reports/post_impl_utilization.rpt}
report_drc -file {E:/dev/edagent-vivado/examples/uart_demo/20260521_215006_test_mock/reports/post_impl_drc.rpt}

puts "INFO: post_impl completed successfully"
exit
