import type { ConnectorCapability, EvidenceManifest, Job, JobRequest } from "./index.ts";

export const REMOTE_SCHEMA_VERSION = "connector.remote.v1" as const;
export type TransportMode = "direct_https" | "outbound_tunnel";
export type AuthMode = "mtls";
export type RegistrationState = "registering" | "approved" | "ready" | "degraded" | "offline" | "revoked";
export type DataClassification = "public" | "internal" | "confidential" | "restricted";
export interface ConnectorEndpoint {
  connector_id:string; display_name:string; endpoint_url:string; protocol_version:string; transport_mode:TransportMode; auth_mode:AuthMode;
  tls_trust_ref:string; tls_client_cert_ref:string; project_scope:readonly string[]; data_classification_scope:readonly DataClassification[];
  allowed_capability_ids:readonly string[]; toolchain_profile_hash:string; worker_labels:Readonly<Record<string,string>>;
  heartbeat_interval_seconds:number; lease_seconds:number; max_concurrency:number; registration_state:RegistrationState;
  created_at:string; updated_at:string; audited_by:string;
  expected_capability_map_version?:string; expected_part_catalog_hash?:string; expected_sdk_worker_build_hash?:string;
}
export interface DiscoverySnapshot { connector_id:string; connector_protocol_version:string; capability_map_version:string; vivado_version:string; vivado_patch:string; part_catalog_hash:string; sdk_worker_build_hash:string; capabilities:readonly ConnectorCapability[]; toolchain_profile_hash:string; license_status:"available"|"unavailable"|"unknown"; unsupported?:readonly string[]; }
export interface ConnectorRegistration extends ConnectorEndpoint { discovered?:DiscoverySnapshot; last_heartbeat_at?:string; lease_expires_at?:string; capability_drift?:boolean; }
export interface RemoteEnvelope<T> { schema_version:typeof REMOTE_SCHEMA_VERSION; correlation_id:string; causation_id?:string; idempotency_key:string; actor:{actor_type:"user"|"service";actor_id:string}; project_id:string; classification:DataClassification; capability_version:string; payload:T; }
export interface RemoteResponse<T> { status:number; body:RemoteEnvelope<T>|{error_code:string;message?:string}; }
export interface RemoteTransport { request(path:string, request:{method:"POST"|"GET";body?:RemoteEnvelope<unknown>}):Promise<RemoteResponse<unknown>>; }
export class RemoteConnectorError extends Error { constructor(public readonly code:string,message=code,public readonly retryable=false){super(message);this.name="RemoteConnectorError";} }
const classes:readonly DataClassification[]=["public","internal","confidential","restricted"], states:readonly RegistrationState[]=["registering","approved","ready","degraded","offline","revoked"], runClasses:readonly string[]=["exploratory","gate_check","formal"], idRe=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/, refRe=/^(secret|vault|cert):\/\/[A-Za-z0-9._~:/-]+$/;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
function required(v:unknown,n:string):asserts v is string{if(typeof v!=="string"||!v.trim())throw new RemoteConnectorError("CONFIG_INVALID",`${n} must be non-empty`);}
function ref(v:unknown,n:string):asserts v is string{required(v,n);if(!refRe.test(v)||v.includes("-----BEGIN"))throw new RemoteConnectorError("SECRET_VALUE_FORBIDDEN",`${n} must be a reference`);}
function validId(v:unknown){return typeof v==="string"&&idRe.test(v);}
function uniqueList(v:unknown,n:string,check:(x:unknown)=>boolean):asserts v is readonly unknown[]{if(!Array.isArray(v)||!v.length||v.some(x=>!check(x))||new Set(v).size!==v.length)throw new RemoteConnectorError("CONFIG_INVALID",`${n} invalid`);}
function validTimestamp(v:unknown,n:string){required(v,n);if(Number.isNaN(Date.parse(v)))throw new RemoteConnectorError("CONFIG_INVALID",`${n} invalid`);}
function allowedHostname(v:unknown,n:string):string{required(v,n);const h=v.trim().toLowerCase();if(!h||h.includes("://")||h.includes("/")||h.includes("*")||h.endsWith("."))throw new RemoteConnectorError("CONFIG_INVALID",`${n} invalid`);return h;}
export function validateConnectorEndpoint(e:ConnectorEndpoint,o:{devMode?:boolean;allowlist:readonly string[]}):ConnectorEndpoint{
 if(!object(e))throw new RemoteConnectorError("CONFIG_INVALID"); for(const n of ["connector_id","display_name","protocol_version","toolchain_profile_hash","audited_by"] as const)required(e[n],n);if(!validId(e.connector_id))throw new RemoteConnectorError("CONFIG_INVALID","connector_id malformed");required(e.endpoint_url,"endpoint_url");let u:URL;try{u=new URL(e.endpoint_url);}catch{throw new RemoteConnectorError("CONFIG_INVALID","endpoint_url malformed");}
 if(u.protocol!=="https:"||u.username||u.password||u.search||u.hash||!u.hostname) { const code=u.protocol!=="https:"?"INSECURE_ENDPOINT":"CONFIG_INVALID"; throw new RemoteConnectorError(code,`${code}: endpoint_url invalid`); } const h=allowedHostname(u.hostname,"endpoint hostname");const allow=(o.allowlist??[]).map(x=>allowedHostname(x,"allowlist hostname"));if(!allow.length||!allow.includes(h))throw new RemoteConnectorError("ENDPOINT_NOT_ALLOWLISTED");
 if(e.protocol_version!==REMOTE_SCHEMA_VERSION)throw new RemoteConnectorError("UNSUPPORTED_PROTOCOL");if(e.transport_mode!=="direct_https")throw new RemoteConnectorError("UNSUPPORTED_TRANSPORT");if(e.auth_mode!=="mtls")throw new RemoteConnectorError("UNSUPPORTED_AUTH");ref(e.tls_trust_ref,"tls_trust_ref");ref(e.tls_client_cert_ref,"tls_client_cert_ref");
 uniqueList(e.project_scope,"project_scope",validId);uniqueList(e.data_classification_scope,"classification scope",x=>typeof x==="string"&&classes.includes(x as DataClassification));uniqueList(e.allowed_capability_ids,"capability scope",validId);if(!object(e.worker_labels)||Object.values(e.worker_labels).some(v=>typeof v!=="string"||!v.trim()))throw new RemoteConnectorError("CONFIG_INVALID","worker_labels invalid");
 if(!Number.isInteger(e.heartbeat_interval_seconds)||e.heartbeat_interval_seconds<1)throw new RemoteConnectorError("CONFIG_INVALID","heartbeat invalid");if(!Number.isInteger(e.lease_seconds)||e.lease_seconds<e.heartbeat_interval_seconds*2)throw new RemoteConnectorError("CONFIG_INVALID","lease invalid");if(!Number.isInteger(e.max_concurrency)||e.max_concurrency<1)throw new RemoteConnectorError("CONFIG_INVALID","concurrency invalid");if(!states.includes(e.registration_state))throw new RemoteConnectorError("CONFIG_INVALID","state invalid");validTimestamp(e.created_at,"created_at");validTimestamp(e.updated_at,"updated_at");for(const n of ["expected_capability_map_version","expected_part_catalog_hash","expected_sdk_worker_build_hash"] as const)if(e[n]!==undefined)required(e[n],n);return structuredClone(e);
}
function validateDiscovery(d:unknown,e:ConnectorEndpoint):DiscoverySnapshot{if(!object(d)||d.connector_id!==e.connector_id||typeof d.connector_protocol_version!=="string"||typeof d.capability_map_version!=="string"||typeof d.vivado_version!=="string"||typeof d.vivado_patch!=="string"||typeof d.part_catalog_hash!=="string"||typeof d.sdk_worker_build_hash!=="string"||typeof d.toolchain_profile_hash!=="string"||!(["available","unavailable","unknown"] as const).includes(d.license_status as never)||!Array.isArray(d.capabilities))throw new RemoteConnectorError("COMPATIBILITY_REJECTED");if(d.connector_protocol_version!==REMOTE_SCHEMA_VERSION)throw new RemoteConnectorError("UNSUPPORTED_PROTOCOL");for(const c of d.capabilities)if(!object(c)||typeof c.operation!=="string"||!validId(c.operation)||typeof c.version!=="string"||!Array.isArray(c.runClasses)||!c.runClasses.length||c.runClasses.some(x=>typeof x!=="string"||!runClasses.includes(x)))throw new RemoteConnectorError("CAPABILITY_UNAVAILABLE");return structuredClone(d as DiscoverySnapshot);}
const makeId=(p:string)=>`${p}-${crypto.randomUUID()}`;
export interface RemoteClientOptions { endpoint:ConnectorEndpoint; transport:RemoteTransport; actor:{actor_type:"user"|"service";actor_id:string}; classification:DataClassification; projectId:string; allowlist:readonly string[]; devMode?:boolean; correlationId?:()=>string; }
export interface ApprovalContext { baselineId?:string; approvedGateResultId?:string; gateSubmissionId?:string; inputApproved?:boolean; projectId?:string; }
function capabilitySupports(d:DiscoverySnapshot|undefined,operation:string,runClass:string,version:string):boolean { const cap=d?.capabilities.find(x=>x.operation===operation); return !!cap&&cap.version===version&&cap.runClasses.includes(runClass); }
export class RemoteConnectorClient {
 private readonly e:ConnectorEndpoint; private readonly t:RemoteTransport; private readonly a:RemoteClientOptions["actor"]; private readonly c:DataClassification; private readonly p:string; private readonly corr:()=>string; private s:RegistrationState; private drift=false; private lease?:number; private discovered?:DiscoverySnapshot;
 constructor(o:RemoteClientOptions){this.e=validateConnectorEndpoint(o.endpoint,o);this.t=o.transport;this.a=o.actor;this.c=o.classification;this.p=o.projectId;this.corr=o.correlationId??(()=>makeId("corr"));if(!this.e.project_scope.includes(this.p))throw new RemoteConnectorError("PROJECT_NOT_ALLOWED");if(!this.e.data_classification_scope.includes(this.c))throw new RemoteConnectorError("CLASSIFICATION_NOT_ALLOWED");this.s=this.e.registration_state;}
 get state(){if(this.lease!==undefined&&Date.now()>=this.lease&&this.s!=="revoked")this.s="offline";return this.s;} get hasCapabilityDrift(){return this.drift;}
 private async call<T>(path:string,payload:unknown,cap:string,key:string,correlation:string):Promise<RemoteEnvelope<T>>{if(this.state==="revoked")throw new RemoteConnectorError("ENDPOINT_REVOKED");const body:RemoteEnvelope<unknown>={schema_version:REMOTE_SCHEMA_VERSION,correlation_id:correlation,idempotency_key:key,actor:this.a,project_id:this.p,classification:this.c,capability_version:cap,payload};const r=await this.t.request(path,{method:"POST",body});if(!r.body||!object(r.body)||r.status<200||r.status>=300||!("payload" in r.body)){const code=object(r.body)&&typeof r.body.error_code==="string"?r.body.error_code:"REMOTE_PROTOCOL_ERROR";throw new RemoteConnectorError(code,code,code!=="unknown_effect"&&r.status>=500);}const x=r.body as unknown as RemoteEnvelope<T>;if(x.schema_version!==REMOTE_SCHEMA_VERSION||x.correlation_id!==correlation||x.idempotency_key!==key||x.project_id!==this.p||x.classification!==this.c||x.capability_version!==cap||!object(x.actor)||x.actor.actor_type!==this.a.actor_type||x.actor.actor_id!==this.a.actor_id)throw new RemoteConnectorError("COMPATIBILITY_REJECTED");return x;}
 async register(){const x=await this.call<ConnectorRegistration>("/registration",{endpoint:this.e},REMOTE_SCHEMA_VERSION,`register:${this.e.connector_id}:${makeId("nonce")}`,this.corr());if(!object(x.payload)||x.payload.connector_id!==this.e.connector_id)throw new RemoteConnectorError("COMPATIBILITY_REJECTED");if(x.payload.registration_state==="revoked")throw new RemoteConnectorError("ENDPOINT_REVOKED");this.s=x.payload.registration_state==="ready"?"approved":x.payload.registration_state;return structuredClone(x.payload);}
 async heartbeat(){if(this.state==="offline")throw new RemoteConnectorError("LEASE_EXPIRED");const x=await this.call<ConnectorRegistration>("/heartbeat",{connector_id:this.e.connector_id},REMOTE_SCHEMA_VERSION,`heartbeat:${this.e.connector_id}:${makeId("nonce")}`,this.corr());if(!object(x.payload)||x.payload.connector_id!==this.e.connector_id)throw new RemoteConnectorError("COMPATIBILITY_REJECTED");if(x.payload.registration_state==="revoked")throw new RemoteConnectorError("ENDPOINT_REVOKED");if(x.payload.registration_state==="ready"&&!x.payload.discovered)throw new RemoteConnectorError("DISCOVERY_REQUIRED");this.s=x.payload.registration_state;this.drift=x.payload.capability_drift===true;if(x.payload.discovered)this.discovered=validateDiscovery(x.payload.discovered,this.e);if(x.payload.lease_expires_at){const lease=Date.parse(x.payload.lease_expires_at);if(Number.isNaN(lease))throw new RemoteConnectorError("CONFIG_INVALID","lease_expires_at invalid");this.lease=lease;if(lease<=Date.now()){this.s="offline";throw new RemoteConnectorError("LEASE_EXPIRED");}}return structuredClone(x.payload);}
 async discover(){const x=await this.call<DiscoverySnapshot>("/discover",{connector_id:this.e.connector_id},REMOTE_SCHEMA_VERSION,`discover:${this.e.connector_id}:${makeId("nonce")}`,this.corr());const d=validateDiscovery(x.payload,this.e);this.discovered=d;this.drift=d.toolchain_profile_hash!==this.e.toolchain_profile_hash||d.connector_protocol_version!==this.e.protocol_version||(this.e.expected_capability_map_version!==undefined&&d.capability_map_version!==this.e.expected_capability_map_version)||(this.e.expected_part_catalog_hash!==undefined&&d.part_catalog_hash!==this.e.expected_part_catalog_hash)||(this.e.expected_sdk_worker_build_hash!==undefined&&d.sdk_worker_build_hash!==this.e.expected_sdk_worker_build_hash)||d.license_status!=="available"||d.capabilities.some(cap=>!this.e.allowed_capability_ids.includes(cap.operation));return structuredClone(d);}
 async status(id:string){required(id,"jobId");return structuredClone((await this.call<Job>("/jobs/status",{job_id:id},"0",`status:${id}:${makeId("nonce")}`,this.corr())).payload);}
 async submit(r:JobRequest,approval?:ApprovalContext){if(this.state==="offline")throw new RemoteConnectorError("LEASE_EXPIRED");if(this.state!=="ready")throw new RemoteConnectorError("ENDPOINT_NOT_APPROVED");if(this.drift)throw new RemoteConnectorError("CAPABILITY_DRIFT");if(r.projectId!==this.p)throw new RemoteConnectorError("PROJECT_SCOPE_MISMATCH");required(r.idempotencyKey,"idempotencyKey");required(r.correlationId,"correlationId");if(!this.e.allowed_capability_ids.includes(r.operation))throw new RemoteConnectorError("CAPABILITY_UNAVAILABLE");const version=(r as JobRequest&{capabilityVersion?:string}).capabilityVersion??this.discovered?.capabilities.find(cap=>cap.operation===r.operation)?.version??"fake-1";if(this.discovered&&!capabilitySupports(this.discovered,r.operation,r.runClass,version))throw new RemoteConnectorError("CAPABILITY_UNAVAILABLE");if(r.runClass==="gate_check"&&!approval?.gateSubmissionId)throw new RemoteConnectorError("GATE_SUBMISSION_REQUIRED");if(r.runClass==="formal"&&(!approval?.inputApproved||(!approval.baselineId&&!approval.approvedGateResultId)||(approval.projectId!==undefined&&approval.projectId!==this.p)))throw new RemoteConnectorError("FORMAL_GATE_REQUIRED");if(r.runClass==="formal"&&r.input.startsWith("candidate:"))throw new RemoteConnectorError("CANDIDATE_FORMAL_REJECTED");const result=(await this.call<Job>("/jobs/submit",{request:r,approval},version,r.idempotencyKey,r.correlationId)).payload;if(!object(result)||!object(result.request)||result.request.projectId!==this.p||result.request.operation!==r.operation||result.request.runClass!==r.runClass||result.request.idempotencyKey!==r.idempotencyKey||result.request.correlationId!==r.correlationId)throw new RemoteConnectorError("COMPATIBILITY_REJECTED");return structuredClone(result as Job);}
 async cancel(id:string){required(id,"jobId");return structuredClone((await this.call<Job>("/jobs/cancel",{job_id:id},"0",`cancel:${id}:${makeId("nonce")}`,this.corr())).payload);} async evidence(id:string){required(id,"jobId");const m=(await this.call<EvidenceManifest>("/jobs/evidence",{job_id:id},"0",`evidence:${id}:${makeId("nonce")}`,this.corr())).payload;if(!object(m)||m.jobId!==id||!Array.isArray(m.entries)||!m.entries.every(e=>object(e)&&typeof e.name==="string"&&/^[a-f0-9]{64}$/.test(String(e.sha256))&&Number.isInteger(e.sizeBytes)&&Number(e.sizeBytes)>=0&&typeof e.mediaType==="string"&&!!e.mediaType))throw new RemoteConnectorError("EVIDENCE_CORRUPT");return structuredClone(m as EvidenceManifest);}
}
