import { describe, expect, test } from "bun:test";
import { RemoteConnectorClient, REMOTE_SCHEMA_VERSION, validateConnectorEndpoint, type ConnectorEndpoint, type RemoteEnvelope, type RemoteResponse, type RemoteTransport } from "./remote.ts";
import type { Job } from "./index.ts";
const endpoint: ConnectorEndpoint={connector_id:"vivado-1",display_name:"remote",endpoint_url:"https://eda.example.test:8443",protocol_version:REMOTE_SCHEMA_VERSION,transport_mode:"direct_https",auth_mode:"mtls",tls_trust_ref:"secret://trust/1",tls_client_cert_ref:"secret://cert/1",project_scope:["p1"],data_classification_scope:["internal"],allowed_capability_ids:["vivado_synthesize"],toolchain_profile_hash:"profile-a",worker_labels:{os:"linux"},heartbeat_interval_seconds:10,lease_seconds:30,max_concurrency:2,registration_state:"registering",created_at:"2026-08-01T00:00:00Z",updated_at:"2026-08-01T00:00:00Z",audited_by:"svc"};
const job={} as Job;
class FakeHttp implements RemoteTransport { calls:{path:string;body:RemoteEnvelope<unknown>}[]=[]; next:(path:string,body:RemoteEnvelope<unknown>)=>RemoteResponse<unknown>; constructor(next:(path:string,body:RemoteEnvelope<unknown>)=>RemoteResponse<unknown>){this.next=next;} async request(path:string,r:{method:"POST"|"GET";body?:RemoteEnvelope<unknown>}){this.calls.push({path,body:r.body!});return this.next(path,r.body!);} }
const ok=<T>(body:RemoteEnvelope<unknown>,payload:T):RemoteResponse<T>=>({status:200,body:{...body,payload} as RemoteEnvelope<T>});
function client(http:RemoteTransport){return new RemoteConnectorClient({endpoint,transport:http,actor:{actor_type:"service",actor_id:"core"},classification:"internal",projectId:"p1",allowlist:["eda.example.test"],correlationId:()=>"fixed-c"});}
describe("remote connector compatibility mode",()=>{
 test("rejects insecure, reserved, unallowlisted, and invalid scope",()=>{expect(()=>validateConnectorEndpoint({...endpoint,endpoint_url:"http://remote"},{allowlist:["remote"]})).toThrow("INSECURE_ENDPOINT");expect(()=>validateConnectorEndpoint({...endpoint,transport_mode:"outbound_tunnel"},{allowlist:["eda.example.test"]})).toThrow("UNSUPPORTED_TRANSPORT");expect(()=>validateConnectorEndpoint(endpoint,{allowlist:[]})).toThrow("ENDPOINT_NOT_ALLOWLISTED");expect(()=>validateConnectorEndpoint({...endpoint,project_scope:[]},{allowlist:["eda.example.test"]})).toThrow("project_scope invalid");});
 test("sends versioned envelope and lifecycle heartbeat",async()=>{const h=new FakeHttp((path,b)=>ok(b,{...endpoint,registration_state:path==="/registration"?"approved":"ready",discovered:{connector_id:"vivado-1",connector_protocol_version:REMOTE_SCHEMA_VERSION,capability_map_version:"1",vivado_version:"2025.1",vivado_patch:"p",part_catalog_hash:"x",sdk_worker_build_hash:"b",capabilities:[],toolchain_profile_hash:"profile-a",license_status:"available"}}));const c=client(h);expect((await c.register()).registration_state).toBe("approved");expect((await c.heartbeat()).registration_state).toBe("ready");expect(h.calls[0]!.body.schema_version).toBe(REMOTE_SCHEMA_VERSION);expect(h.calls[0]!.body.correlation_id).toBe("fixed-c");expect(h.calls[0]!.body.idempotency_key).toMatch(/^register:/);});
 test("discovers drift and blocks formal",async()=>{const d={connector_id:"vivado-1",connector_protocol_version:REMOTE_SCHEMA_VERSION,capability_map_version:"1",vivado_version:"2025.1",vivado_patch:"p",part_catalog_hash:"x",sdk_worker_build_hash:"b",capabilities:[],toolchain_profile_hash:"profile-a",license_status:"available"} as const;const h=new FakeHttp((path,b)=>ok(b,path==="/discover"?{...d,toolchain_profile_hash:"different"}:{...endpoint,registration_state:"ready",discovered:d}));const c=client(h);await c.register();await c.heartbeat();await c.discover();expect(c.hasCapabilityDrift).toBe(true);await expect(c.submit({idempotencyKey:"k",projectId:"p1",operation:"vivado_synthesize",runClass:"formal",input:"x",correlationId:"c"},{baselineId:"b",inputApproved:true})).rejects.toThrow("CAPABILITY_DRIFT");});
 test("enforces formal, gate-check, candidate, and project boundaries",async()=>{const d={connector_id:"vivado-1",connector_protocol_version:REMOTE_SCHEMA_VERSION,capability_map_version:"1",vivado_version:"2025.1",vivado_patch:"p",part_catalog_hash:"x",sdk_worker_build_hash:"b",capabilities:[{operation:"vivado_synthesize",version:"fake-1",runClasses:["exploratory","gate_check","formal"]}],toolchain_profile_hash:"profile-a",license_status:"available"} as const;const h=new FakeHttp((path,b)=>ok(b,{...endpoint,registration_state:path==="/heartbeat"?"ready":"approved",discovered:d}));const c=client(h);await c.register();await c.heartbeat();await expect(c.submit({idempotencyKey:"k",projectId:"p1",operation:"vivado_synthesize",runClass:"formal",input:"x",correlationId:"c"})).rejects.toThrow("FORMAL_GATE_REQUIRED");await expect(c.submit({idempotencyKey:"k",projectId:"p1",operation:"vivado_synthesize",runClass:"gate_check",input:"x",correlationId:"c"})).rejects.toThrow("GATE_SUBMISSION_REQUIRED");await expect(c.submit({idempotencyKey:"k",projectId:"p2",operation:"vivado_synthesize",runClass:"exploratory",input:"x",correlationId:"c"})).rejects.toThrow("PROJECT_SCOPE_MISMATCH");});
 test("uses request idempotency/correlation and rejects mismatched response",async()=>{const d={connector_id:"vivado-1",connector_protocol_version:REMOTE_SCHEMA_VERSION,capability_map_version:"1",vivado_version:"2025.1",vivado_patch:"p",part_catalog_hash:"x",sdk_worker_build_hash:"b",capabilities:[{operation:"vivado_synthesize",version:"fake-1",runClasses:["exploratory"]}],toolchain_profile_hash:"profile-a",license_status:"available"} as const;const h=new FakeHttp((path,b)=>ok(b,path==="/heartbeat"?{...endpoint,registration_state:"ready",discovered:d}:job));const c=client(h);await c.register();await c.heartbeat();await c.submit({idempotencyKey:"job-key",projectId:"p1",operation:"vivado_synthesize",runClass:"exploratory",input:"x",correlationId:"job-correlation"});const call=h.calls.at(-1)!;expect(call.body.idempotency_key).toBe("job-key");expect(call.body.correlation_id).toBe("job-correlation");const bad=new FakeHttp((_,b)=>ok({...b,correlation_id:"wrong"},job));await expect(client(bad).register()).rejects.toThrow("COMPATIBILITY_REJECTED");});
 test("rejects incompatible and preserves unknown-effect non-retry",async()=>{const bad=new FakeHttp((_,b)=>ok({...b,schema_version:"connector.remote.v0"},job));await expect(client(bad).register()).rejects.toThrow("COMPATIBILITY_REJECTED");const fail=new FakeHttp(()=>({status:409,body:{error_code:"unknown_effect"}}));await expect(client(fail).register()).rejects.toMatchObject({code:"unknown_effect",retryable:false});});
});
